<Project Sdk="Microsoft.NET.Sdk.Worker">
  <PropertyGroup>
    <TargetFramework>net7.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>TronSoft.Agent.Windows</AssemblyName>
    <RootNamespace>TronSoft.Agent.Windows</RootNamespace>
    <Version>0.1.6.0</Version>
    <AssemblyVersion>0.1.6.0</AssemblyVersion>
    <FileVersion>0.1.6.0</FileVersion>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="7.0.20" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="7.0.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="7.0.1" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="7.0.1" />
    <PackageReference Include="System.Diagnostics.PerformanceCounter" Version="7.0.0" />
    <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="7.0.0" />
  </ItemGroup>
  <ItemGroup>
    <Content Remove="publish\**" />
    <Content Remove="publish-win-x64\**" />
    <Content Remove="installer-win-x64\**" />
    <None Remove="publish\**" />
    <None Remove="publish-win-x64\**" />
    <None Remove="installer-win-x64\**" />
  </ItemGroup>
</Project>
